'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cs_keys
    Public Property key_id As Integer
    Public Property user_id As Integer
    Public Property key_code As String
    Public Property key_day As Integer
    Public Property key_who As String
    Public Property key_statu As Boolean

End Class
