'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cs_settings
    Public Property cs_setID As Integer
    Public Property cs_message As String
    Public Property cs_messageactive As Boolean
    Public Property cs_date As Date
    Public Property cs_active As Boolean
    Public Property cs_loginactive As Boolean
    Public Property cs_freetime As Boolean

End Class
