'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cs_users
    Public Property user_id As Integer
    Public Property user_name As String
    Public Property user_pass As String
    Public Property user_createdate As Date
    Public Property user_lastlogin As Date
    Public Property user_enddate As Date
    Public Property user_online As Boolean
    Public Property user_hdd As String

End Class
