'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ICExProject
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ICExProject")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property cs_keys() As DbSet(Of cs_keys)
    Public Overridable Property cs_settings() As DbSet(Of cs_settings)
    Public Overridable Property cs_users() As DbSet(Of cs_users)

End Class
